server:
  forward-headers-strategy: framework

spring:
  config:
    import:
      - file:env/prod.env[.properties]

  application:
    name: history-prod

  aot:
    enabled: false  # AOT 비활성화

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 30MB

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  task:
    scheduling:
      enabled: true
    execution:
      pool:
        core-size: 2
        max-size: 10
        queue-capacity: 100


jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}


logging:
  level:
    root: INFO
    org:
      springframework:
        web: ERROR
    org.springframework.web.cors: TRACE
    org.springframework.web.filter.CorsFilter: TRACE
    org.springframework.web.util: TRACE


oauth2:
  front-url: ${OAUTH2_FRONT_URL}

  kakao:
    base-url: ${KAKAO_OAUTH2_BASE_URL}
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    front-redirect-uri: ${KAKAO_FRONT_REDIRECT_URI}

  naver:
    base-url: ${NAVER_OAUTH2_BASE_URL}
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URI}

  apple:
    client-id: ${APPLE_CLIENT_ID}
    team-id: ${APPLE_TEAM_ID}
    key-id: ${APPLE_KEY_ID}
    private-key: ${APPLE_PRIVATE_KEY}
    redirect-uri: ${APPLE_REDIRECT_URI}
    profile: ${APPLE_PROFILE}


admin:
  id: ${ADMIN_ID}


cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

openai:
  api:
    url: https://api.openai.com
    key: ${OPENAI_API_KEY}
  text:
    model: gpt-4o


